### ISSUE TITLE
README.md + License

### ISSUE THREAD

**Issue by jbenet** [whyrusleeping/multiaddr-filter#1]
otherwise it's not trivially easy for people to use a repo

**Comment by whyrusleeping** [comment]
i hate licensing. Cant i just put something somewhere on my github stating "MIT unless otherwise noted" ?

**Comment by jbenet** [comment]
people do it all the time (i used to do it all the time) but it doesn't hold up in court.

**Comment by jbenet** [comment]
closed in #2
